from agent_ppo.conf.conf import Config


LOCAL_VIEW_SHAPE = Config.LOCAL_VIEW_SHAPE
LOCAL_VIEW_DIM = Config.LOCAL_VIEW_DIM
MISSION_ENCODING_DIM = Config.MISSION_MAX_LEN * Config.MISSION_CHAR_CODES
OBS_DIM = Config.OBS_DIM
ACTION_NUM = Config.ACTION_NUM
VALUE_NUM = Config.VALUE_NUM

